### ISSUE TITLE
Separator ve Rainbow Line hatası.

### ISSUE THREAD

**Issue by Aleaf-Egemen** [Cryfix/EasyClient#1]
Sol kısımdan biraz kayık.

![image](https://user-images.githubusercontent.com/45121448/114306268-11fdd180-9ae4-11eb-8afb-059688081917.png)
![image](https://user-images.githubusercontent.com/45121448/114306278-1b873980-9ae4-11eb-93d9-29d5100f922a.png)

**Comment by Cryfix** [comment]
Gui tamamen değişecek. Bu hatada düzeltilecek. Teşekkürler.
