### ISSUE TITLE
Kullancı configleri ve hazır configler

### ISSUE THREAD

**Issue by Aleaf-Egemen** [Cryfix/EasyClient#10]
Easy kullanıcıları kendi kişiselleştirilmiş configlerini kaydedebilir veya hazır configleri kullanabilir.

**Comment by Cryfix** [comment]
Zaten önceden yaptığımız bir sistem ama kalıcı bir hostingimiz olmadığı için kullanıma sunmadığımız bir sistem. Belki ileride.
