### ISSUE TITLE
Screenshare Bypass

### ISSUE THREAD

**Issue by Aleaf-Egemen** [Cryfix/EasyClient#13]
Easy Loader herzaman appdata klasörüne indirme yaptığı için kolayca tespit edilinebiliyor.

**Comment by Aleaf-Egemen** [comment]
![Uploading image.png…]()

**Comment by Aleaf-Egemen** [comment]
![image](https://user-images.githubusercontent.com/45121448/114309456-d1a45080-9aef-11eb-8240-12ba30165c17.png)
![image](https://user-images.githubusercontent.com/45121448/114309473-dcf77c00-9aef-11eb-844d-e71cb9839cca.png)

**Comment by Cryfix** [comment]
Daha sonraki güncellemelerde umarım
