### ISSUE TITLE
Theme hatası

### ISSUE THREAD

**Issue by Aleaf-Egemen** [Cryfix/EasyClient#4]
![image](https://user-images.githubusercontent.com/45121448/114306499-c1d33f00-9ae4-11eb-9d23-6c6021b67cb9.png)
![image](https://user-images.githubusercontent.com/45121448/114306547-cc8dd400-9ae4-11eb-81f3-88da8c9b57ae.png)
Renk seçici bar'ın yarısından sonra yuvarlak imleç siyah oluyor

**Comment by Cryfix** [comment]
Arkaplan rengine uyum sağlamak için (rengin içinde kaybolmamak için) böyle bir özellik mevcut. Bu bir sorun değil.
