### ISSUE TITLE
Title detector

### ISSUE THREAD

**Issue by Aleaf-Egemen** [Cryfix/EasyClient#5]
Tuşlar ve makro özellikleri "CraftRise & SonOyuncu" içeren heryerde çalışıyor (Websitesi veya CraftRise olarak isimlendirilmiş not defteri).

**Comment by Cryfix** [comment]
Hayır. Sadece javaw, java uygulaması ve belirli titlelerde çalışır.

**Comment by Aleaf-Egemen** [comment]
> Hayır. Sadece javaw, java uygulaması ve belirli titlelerde çalışır.

cok bilion dene gor mal
